version: '3'
services:
  nginx:
      image: nginx:1.13
      container_name: nginx
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./www:/usr/share/nginx/html
        - ./conf.d:/etc/nginx/conf.d
        - ./nginx.conf:/etc/nginx/nginx.con
        - ./log:/var/log/nginx
networks:
  default:
    external:
      name: docker-network